name: Print Hello

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        required: true
        default: 'Hello from workflow_dispatch'

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Print Message
      run: |
        if [ -z "${{ github.event.inputs.message }}" ]; then
          echo "Hello from push or pull request"
        else
          echo "${{ github.event.inputs.message }}"
        fi
